### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by qwexvf** [ashleysommer/sanic-cors#2]
i got some issue!
```
ERROR:sanic:Traceback (most recent call last):
  File "/home/xyz/.pyenv/versions/sanic/lib/python3.6/site-packages/sanic/app.py", line 455, in handle_request
    _response = await _response
  File "/home/xyz/.pyenv/versions/sanic/lib/python3.6/site-packages/sanic_cors/extension.py", line 181, in cors_response_middleware
    if resp.headers.get(ACL_ORIGIN):
AttributeError: 'NoneType' object has no attribute 'headers'
```
Thanks!

**Comment by ashleysommer** [comment]
Hi @qwexvf 
I will look into this for you.
Are you able to give any more details of the problem? Can you write a small application that reproduces this error?
I see you are on python 3.6. I don't test on 3.6 because I only have 3.5 installed. It might be 3.6 related, but it might be a bug in my extension.

**Comment by ashleysommer** [comment]
Ok, it looks as if somehow `response.headers` is set to `None` when the CORS extension is called.

`response.headers` should never be `None`. If no headers are passed to a response creator, sanic sets headers to `{}`, empty dict.

If you are explicitly setting `response.headers = None` somewhere in your code, that will break most extensions.

**Comment by ashleysommer** [comment]
Closing as invalid

**Comment by qwexvf** [comment]
No, I didn't set to None,
```
2017-04-15 04:52:06,147: ERROR: Traceback (most recent call last):
  File "/home/xyz/.pyenv/versions/sanic/lib/python3.6/site-packages/sanic/app.py", line 471, in handle_request
    response = handler(request, *args, **kwargs)
  File "/home/xyz/.pyenv/versions/sanic/lib/python3.6/site-packages/sanic_cors/decorator.py", line 134, in wrapped_function
    set_cors_headers(req, resp, options)
  File "/home/xyz/.pyenv/versions/sanic/lib/python3.6/site-packages/sanic_cors/core.py", line 235, in set_cors_headers
    if not isinstance(resp.headers, CIDict):
AttributeError: 'coroutine' object has no attribute 'headers'
```
Now i got this!

**Comment by qwexvf** [comment]
And on the browser console i got this
```
XMLHttpRequest cannot load http://localhost:8000/api/auth/request-token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.14:8080' is therefore not allowed access. The response had HTTP status code 404.
```
any advice ?

**Comment by qwexvf** [comment]
Sorry ignore all of them. i was running the examples which those routes does not exist lol.
sorry i was so dumb.

Nice extension <3 keep it up!

**Comment by r0fls** [comment]
@qwexvf can you make sure you're using the latest version of this module? ```File "/home/xyz/.pyenv/versions/sanic/lib/python3.6/site-packages/sanic_cors/extension.py", line 181, in cors_response_middleware
    if resp.headers.get(ACL_ORIGIN):``` that line is apparently occurring at 237 now (not 181) https://github.com/ashleysommer/sanic-cors/blob/master/sanic_cors/extension.py#L237 so it's quite hard to debug...

**Comment by ashleysommer** [comment]
Im going to reopen this issue,
Even though I cannot reproduce it, I believe it may affect others now or in the future.

I think it has something to do with the extension attempting to modify the headers of an Exception response

**Comment by qwexvf** [comment]
@r0fls since now im using cors to specific resource i'm not having this issue anymore.
not sure but maybe the problem was the websockets..

**Comment by ashleysommer** [comment]
I believe this issue was created before Websockets were added to Sanic.
It was not the cause for the original problem.

It is possible that when this issue was opened, the error caused by using the example code on routes which did not exist, and now the same error is seen when Websockets are used with Sanic-CORS.

**Comment by ashleysommer** [comment]
This should be fixed by: https://github.com/ashleysommer/sanic-cors/commit/6d88deb3a2351c9f91d91006cbceb1706d49f575
This is released on version 0.5.4.1
I also found a versioning bug which means that updating using pip might (from the pypi dist) might not have been working correctly. This is fixed in 0.5.4.1 so you should be able to upgrade correctly now.

**Comment by vromanov** [comment]
Hi all, 
Have the same problem on latest sanic + sanic_cors
Error is `AttributeError: 'NoneType' object has no attribute 'headers'`.
It means that response is None and it happens on websocket handler.
https://github.com/ashleysommer/sanic-cors/commit/6d88deb3a2351c9f91d91006cbceb1706d49f575 doesn't fix the issue because it checks resp.headers for None instead of resp.
I think it shoud be code like 
`if resp is None:
     return`
in cors_response_middleware function.

sanic version: 0.6.0
sanic_cors: 0.6.0.0
error: 
`Exception occured in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 527, in handle_request
    response)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 660, in _run_response_middleware
    _response = await _response
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/extension.py", line 256, in cors_response_middleware
    set_cors_headers(req, resp, res_options)
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/core.py", line 237, in set_cors_headers
    if not isinstance(resp.headers, CIDict):
AttributeError: 'NoneType' object has no attribute 'headers'
`

**Comment by ashleysommer** [comment]
Thanks for the report.

I am aware sanic-cors does not currently work on websocket connections.

I can push a patch later today to fix that crash.

**Comment by ashleysommer** [comment]
@vromanov 
I've released sanic-cors v 0.6.0.1
Can you please test if this fixes your issue.

**Comment by vromanov** [comment]
Thanks for the quick support! It works perfectly!

**Comment by boboldehampsink** [comment]
I still see this issue:

```
ERROR:sanic.error:Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 597, in handle_request
    response = await response
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 597, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 781, in _run_response_middleware
    _response = await _response
  File "/usr/local/lib/python3.6/site-packages/spf/framework.py", line 501, in run_bp_post_response_mw
    _response = await _response
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/extension.py", line 306, in cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/core.py", line 247, in set_cors_headers
    if not isinstance(resp.headers, CIDict):
AttributeError: 'coroutine' object has no attribute 'headers'
```
