### ISSUE TITLE
Chrome still blocks the request although sanic-cors is registered

### ISSUE THREAD

**Issue by skynyrd** [ashleysommer/sanic-cors#5]
Hi,

I have a Sanic (v.0.4.1) REST API (host:127.0.0.1:8000) and ReactJS front end application served on 127.0.0.1:3000. I use blueprints in Sanic application but to explain my problem efficiently, I have simplified them. I simply get an error: 

`XMLHttpRequest cannot load http://127.0.0.1:8000/timeline. Response for preflight has invalid HTTP status code 405`

I already tried different registration ways described in repository home page. I am posting my code below.

My Sanic Application:
```
from sanic import Sanic
from sanic.response import json
from sanic_cors import CORS, cross_origin
from auth_decorator import authorized
from domain.dto.tweet import Tweet
from domain.user import User
from routes.authentication import auth_route
from routes.user import user_route
from routes.tweet import tweet_route
import config
from services.twitter_api import TwitterApi

app = Sanic(__name__)
CORS(app)
# cors = CORS(app, resources={r"/*": {"origins": "*"}})

twitter_api = TwitterApi()


@app.route('/timeline')
# @cross_origin(app)
@authorized()
async def get_timeline(request, user):
    user = User.load(user)
    twitter_api.assign_user(user.token, user.secret)

    raw_timeline_tweets = twitter_api.get_home_timeline()
    timeline_tweets = [Tweet(raw_timeline_tweet) for raw_timeline_tweet in raw_timeline_tweets]

    return json({"timeline": timeline_tweets})


app.blueprint(auth_route, url_prefix="/auth")
app.blueprint(user_route, url_prefix="/user")
app.blueprint(tweet_route, url_prefix='/tweet')

app.run(host=config.APP_HOST_URL, port=config.APP_PORT, debug=True)
```

This is OPTION response headers for `/timeline` endpoint fetched from Google Dev Tools
```
Request URL:http://127.0.0.1:8000/timeline
Request Method:OPTIONS
Status Code:405 Method Not Allowed
Remote Address:127.0.0.1:8000
Referrer Policy:no-referrer-when-downgrade
HTTP/1.1 405 Method Not Allowed
Connection: keep-alive
Keep-Alive: 60
access-control-allow-origin: http://127.0.0.1:3000
access-control-allow-headers: authorization
access-control-max-age: None
access-control-allow-methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
vary: Origin
content-length: 51
content-type: text/plain; charset=utf-8
```

Thanks.

**Comment by ashleysommer** [comment]
@skynyrd Thanks for taking the time to file this issue report.
I see the problem, and it is due to my bad porting of the example files from Flask-CORS to Sanic-CORS.

The problem is that by default Sanic accepts only 'GET' requests for all routes. That means all other request types including 'HEAD','POST', 'PUT','DELETE' and 'OPTIONS' return a 405 "Method not allowed" response.

Flask-CORS has a config option called 'Automatic Options' (which is `True` by default) that handles 'OPTIONS' requests automatically. This was ported to Sanic-CORS , however this is less useful in Sanic because the sanic router will reject the request with 'Method not allowed' before invoking the route, so sanic-cors cannot handle the OPTIONS automatically.

You can fix your example in one of a few ways.
1) Change the sanic route decorator to the following:
`@app.route('/timeline', methods=['GET', 'OPTIONS'])`
Now your example will work correctly, CORS headers will be added, but it will return the same content as the 'GET' request when requesting 'OPTIONS'.
2) Same as `1)` above but return an empty response on an 'OPTIONS' request. (CORS headers will still be applied). Like so:
```
@app.route('/timeline', methods=['GET', 'OPTIONS'])
async def get_timeline(request, user):
    if request.method == "OPTIONS":
        return HTTPResponse()
    ...
```
3) Use the `cross_origin` decorator. The `cross_origin` decorator will do the same as `2)` automatically so you can do this:
```
@app.route('/timeline', methods=["GET", "OPTIONS"])
@cross_origin(app)
async def get_timeline(request, user):
    ...
```

I have updated the `app_based_example` and `blueprints_based_example` example files so that they work, using method `1)` above.

I am currently working an a new release that fixes this whole issue by using a sanic request middleware that intercepts the request before passing it to the sanic router, to do _real_ automatic 'OPTIONS' handling, however this breaks functional-equivalence with flask-CORS. This feature will be in the next release. 

For interest's sake, I tested this example using blueprints too, and with blueprints the problem is different, and more severe.
In the last update I merged a pull-request from a user which adds exception-handling support, so CORS headers will be still applied when Sanic responds with an exceptions.

It turns out that this addition broke CORS on blueprints, so Sanic was raising an exception when registering CORS on a blueprint, and causing the whole app to not work. I have pushed a fix for this too, and it will also be in the next release.

**Comment by ashleysommer** [comment]
UPDATE:
I have pushed the update that fixes the blueprint issue, and adds an app-wide "Automatic Options" config option. The new version is `0.4.1.4`. This config option is False by default, as turning it on means you cannot override routes with custom CORS options, so for compatibility it is turned off by default.

To enable it, do:
`CORS(app, automatic_options=True)`
Now you don't need to worry about putting "OPTIONS" in your allowed methods, or handling the "OPTIONS" request yourself.

**Comment by skynyrd** [comment]
Thank you for your gentle reply, I am going to check new version today and update this post.

**Comment by ashleysommer** [comment]
Please note, I have pushed another new version now (0.5.1.0) that adds compatibility with Sanic v0.5.1, however I have ensured it still works on Sanic 0.4.1 too.

**Comment by skynyrd** [comment]
I have just upgraded `sanic-cors` to `v0.5.1` and it works perfect for now, I also use blueprints. I am going to try it with `PUT` `POST` and `DELETE` verbs too, just perfect for `GET` and `OPTIONS`. 

Thank you very much for your support!

**Comment by ashleysommer** [comment]
Woops, forgot to close this.

**Comment by boylegu** [comment]
CORS(app, automatic_options=True)...... I suggest add to document or README.md.

**Comment by auyer** [comment]
This issue is still happening without the `CORS(app, automatic_options=True)`
The README suggests that `CORS(app)` will use the default options ( and allow everything). 
I believe either `CORS(app)` should do the same as with the ` automatic_options=True` arg, or this should be in docs like @boylegu pointed. I can look into opening a PR for either of the solutions if you want @ashleysommer .

**Comment by ashleysommer** [comment]
@auyer Yes, please open a PR with this added to the readme.
